name: build

on:
  pull_request:
    branches: [main]

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and set Java version
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install and set Flutter channel
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and set Java version
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install and set Flutter channel
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Build for iOS
        run: flutter build ios --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and set Java version
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install and set Flutter channel
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Build App Bundle
        run: flutter build appbundle
